version: '2'

services:
  default:
    image: example-default:latest
    container_name: example_default
    restart: always
    volumes:
      - ./../../shared:/shared
    ports:
      - 8000:80
    env_file:
      - ./deploy/config.sh
