version: '2'

services:
  default:
    image: rails_project:latest
    container_name: rails_project
    restart: always
    volumes:
      - ./../../shared:/shared
    ports:
      - 3000:80
    env_file:
      - ./config/deploy/config.sh
